name: CI/CD for series build app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: trandinhthangv1/api-app:latest
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop api-app
            docker rm api-app
            docker pull ${{ secrets.DOCKER_USERNAME }}/api-app:latest
            docker run -d --name api-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/api-app:latest
