name: CI

on:
  push:
    branches:
      - developer

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
